fix: remove builtins - only externals
smart-data-models/data-models pull request #38
Opened 2022-09-26 06:11 UTC by auphofBSF

fix: poetry install issue as show in PR #37 

INSTALL_REQUIRES should not be builtins

Additionally 2 new dependencies are listed `validate` and `datetime`  and don't appear to be used, 
the source code for `validate` is only available as a tar package and no maintenance visible on [pypa](https://pypi.org/project/validate/)

2022-09-27 11:11 UTC, albertoabellagarcia commented
Regarding validate, we were doing some tests about creating a function (or class) to validate payloads according to the schemas. 
Validate was one option but certainly, there could be others
It was not included yet and maybe in the first official version it will not be there.

2022-09-27 17:58 UTC, auphofBSF commented
I thought that there may be some intention like this. I am using the `schema.json` to automatically build 2 sets of python classes 

-1 a [pydantic](https://pydantic-docs.helpmanual.io/) model automatically generated , these automatically have validation derived from `schema.json`
-2 a further ORM  enriched instance of the model  for rich database persistence and functionality.
-3 all of this generation to be derived from `schema.json` and a minimal configuration dataset

The idea that an example  from a Data Model can be parsed, validated and regenerated from the type1 pydantic model and then be able to persisted/queried by the ORM enriched object against any database backend and back to the type1 object (Full roundtrip). I have this functioning on a few data-models and utilizing `pysmartdatamodels` I am about to test against a larger set that we are interested in . I don't see why we will not be able to contribute this

2022-09-29 05:21 UTC, wistefan requested changes
Looks good, except the datetime. It should stay in the requirements.

2022-09-29 05:21 UTC, wistefan commented on pysmartdatamodels/setup.py
> +    # "validate", # Does not appear to be used
datetime is used:
https://github.com/smart-data-models/data-models/blob/master/pysmartdatamodels/pysmartdatamodels.py#L349

2022-09-29 09:24 UTC, merged